// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/bigartists/Direwolf/client"
	"github.com/bigartists/Direwolf/internal/module/model"
	"github.com/bigartists/Direwolf/internal/module/user"
	"github.com/bigartists/Direwolf/internal/routers"
	"github.com/bigartists/Direwolf/pkg/middlewares"
	"github.com/bigartists/Direwolf/server"
)

// Injectors from wire.go:

func InitializeApp() (*server.App, error) {
	db := client.ProvideDB()
	iUserRepo := user.ProvideUserRepo(db)
	iUserService := user.ProvideUserService(iUserRepo)
	userController := user.ProvideUserController(iUserService)
	iModelRepo := model.ProvideModelRepo(db)
	iModelService := model.ProvideModelService(iModelRepo)
	modelController := model.ProvideModelController(iModelService)
	authMiddleware := middlewares.NewAuthMiddleware(iUserRepo)
	engine := routers.ProvideRouter(userController, modelController, authMiddleware)
	app := server.ProvideApp(engine)
	return app, nil
}
